#!/bin/bash

set -e
 
command=$1
opt=$2
docker_path=`which docker.io || which docker`

cd "$(dirname "$0")"


usage () {
  echo
  echo "Usage:"
  echo ""
}

case "$command" in

  build)
    base/launcher build
    java8/launcher build
    tomcat8/launcher build
 
    exit 0
    ;;

esac

usage
